Author: Jenny Chen

In [1]:
import pandas as pd
import geopandas as gpd
import libpysal as lps
import seaborn as sns
import numpy as np
import tobler as tob
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [20, 10]

In [5]:
dropout = pd.read_parquet('../dropout_count.parquet')

In [6]:
dropout

                 Dropout_Count
CountyName
Alameda                67080.0
Amador                   336.0
Butte                  12754.0
Calaveras                774.0
Colusa                   820.0
Contra Costa           39782.0
Del Norte               1238.0
El Dorado               5559.0
Fresno                 89441.0
Glenn                   3113.0
Humboldt                3064.0
Imperial               18408.0
Inyo                   13298.0
Kern                   61765.0
Kings                   8390.0
Lake                    4881.0
Lassen                   572.0
Los Angeles           577832.0
Madera                  8336.0
Marin                   8921.0
Mariposa                 228.0
Mendocino               6110.0
Merced                 15175.0
Modoc                    424.0
Mono                    5770.0
Monterey               23354.0
Napa                    6594.0
Nevada                 10004.0
Orange                108576.0
Placer                 17704.0
Plumas                   774.0
Riverside              97699.0
Sacramento             77704.0
San Benito              4400.0
San Bernardino        196184.0
San Diego             172239.0
San Francisco          34021.0
San Joaquin            75011.0
San Luis Obispo         7161.0
San Mateo              26442.0
Santa Barbara          20801.0
Santa Clara           150978.0
Santa Cruz             19930.0
Shasta                  7932.0
Sierra                    48.0
Siskiyou                1548.0
Solano                 24519.0
Sonoma                 31115.0
Stanislaus             47784.0
State                 776210.0
Sutter                  8853.0
Tehama                  2324.0
Trinity                  691.0
Tulare                 27995.0
Tuolumne                1595.0
Ventura                42100.0
Yolo                    7937.0
Yuba                    5260.0

In [7]:
dropout.shape

(58, 1)

In [8]:
counties = gpd.read_parquet('../ca_counties_geoid.parquet')

In [9]:
counties.head()

,STATEFP,COUNTYFP,COUNTYNS,GEOID,NAME,NAMELSAD,LSAD,CLASSFP,MTFCC,CSAFP,CBSAFP,METDIVFP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
8,06,091,00277310,06091,Sierra,Sierra County,06,H1,G4020,None,None,None,A,2468694587,23299110,+39.5769252,-120.5219926,"POLYGON ((-120.65559 39.69356, -120.65552 39.6..."
325,06,067,00277298,06067,Sacramento,Sacramento County,06,H1,G4020,472,40900,None,A,2500490904,74894369,+38.4500161,-121.3404408,"POLYGON ((-121.18857 38.71431, -121.18731 38.7..."
329,06,083,00277306,06083,Santa Barbara,Santa Barbara County,06,H1,G4020,None,42200,None,A,7083976828,2729838280,+34.5370572,-120.0399729,"MULTIPOLYGON (((-120.73429 34.90069, -120.7343..."
346,06,009,01675885,06009,Calaveras,Calaveras County,06,H1,G4020,None,None,None,A,2641829200,43797659,+38.1838996,-120.5614415,"POLYGON ((-120.63093 38.34110, -120.63057 38.3..."
394,06,111,00277320,06111,Ventura,Ventura County,06,H1,G4020,348,37100,None,A,4771968316,947365005,+34.3587415,-119.1331432,"MULTIPOLYGON (((-119.32922 34.22784, -119.3292..."

In [10]:
counties = counties[['GEOID','NAMELSAD','NAME','geometry']]

In [11]:
counties.head()

,GEOID,NAMELSAD,NAME,geometry
8,06091,Sierra County,Sierra,"POLYGON ((-120.65559 39.69356, -120.65552 39.6..."
325,06067,Sacramento County,Sacramento,"POLYGON ((-121.18857 38.71431, -121.18731 38.7..."
329,06083,Santa Barbara County,Santa Barbara,"MULTIPOLYGON (((-120.73429 34.90069, -120.7343..."
346,06009,Calaveras County,Calaveras,"POLYGON ((-120.63093 38.34110, -120.63057 38.3..."
394,06111,Ventura County,Ventura,"MULTIPOLYGON (((-119.32922 34.22784, -119.3292..."

In [12]:
counties = counties.rename(columns={'NAME':'CountyName'})

In [13]:
counties.head()

,GEOID,NAMELSAD,CountyName,geometry
8,06091,Sierra County,Sierra,"POLYGON ((-120.65559 39.69356, -120.65552 39.6..."
325,06067,Sacramento County,Sacramento,"POLYGON ((-121.18857 38.71431, -121.18731 38.7..."
329,06083,Santa Barbara County,Santa Barbara,"MULTIPOLYGON (((-120.73429 34.90069, -120.7343..."
346,06009,Calaveras County,Calaveras,"POLYGON ((-120.63093 38.34110, -120.63057 38.3..."
394,06111,Ventura County,Ventura,"MULTIPOLYGON (((-119.32922 34.22784, -119.3292..."

In [14]:
counties.shape

(58, 4)

In [15]:
dropout = gpd.GeoDataFrame(dropout)

In [16]:
school_dropout = dropout.merge(counties, on='CountyName')

In [17]:
school_dropout

,CountyName,Dropout_Count,GEOID,NAMELSAD,geometry
0,Alameda,67080.0,06001,Alameda County,"POLYGON ((-122.28088 37.70723, -122.28178 37.7..."
1,Amador,336.0,06005,Amador County,"POLYGON ((-121.02729 38.48136, -121.02729 38.4..."
2,Butte,12754.0,06007,Butte County,"POLYGON ((-121.85650 39.53358, -121.85638 39.5..."
3,Calaveras,774.0,06009,Calaveras County,"POLYGON ((-120.63093 38.34110, -120.63057 38.3..."
4,Colusa,820.0,06011,Colusa County,"POLYGON ((-122.08018 39.41420, -122.07996 39.4..."
5,Contra Costa,39782.0,06013,Contra Costa County,"POLYGON ((-122.26764 37.90425, -122.26781 37.9..."
6,Del Norte,1238.0,06015,Del Norte County,"POLYGON ((-124.31611 41.72839, -124.33061 41.7..."
7,El Dorado,5559.0,06017,El Dorado County,"POLYGON ((-121.11862 38.71712, -121.11876 38.7..."
8,Fresno,89441.0,06019,Fresno County,"POLYGON ((-120.42219 36.84014, -120.42172 36.8..."
9,Glenn,3113.0,06021,Glenn County,"POLYGON ((-122.89094 39.64487, -122.89134 39.6..."
10,Humboldt,3064.0,06023,Humboldt County,"POLYGON ((-124.28140 40.79915, -124.28018 40.7..."
11,Imperial,18408.0,06025,Imperial County,"POLYGON ((-114.72653 32.71824, -114.72662 32.7..."
12,Inyo,13298.0,06027,Inyo County,"POLYGON ((-118.33758 36.65480, -118.33773 36.6..."
13,Kern,61765.0,06029,Kern County,"POLYGON ((-119.91366 35.43926, -119.92327 35.4..."
14,Kings,8390.0,06031,Kings County,"POLYGON ((-119.95892 36.25547, -119.95893 36.2..."
15,Lake,4881.0,06033,Lake County,"POLYGON ((-123.06515 39.05918, -123.06515 39.0..."
16,Lassen,572.0,06035,Lassen County,"POLYGON ((-121.32191 40.65496, -121.32181 40.6..."
17,Los Angeles,577832.0,06037,Los Angeles County,"MULTIPOLYGON (((-118.70339 34.16859, -118.7033..."
18,Madera,8336.0,06039,Madera County,"POLYGON ((-120.10639 37.16715, -120.10577 37.1..."
19,Marin,8921.0,06041,Marin County,"POLYGON ((-122.78639 37.88695, -122.78704 37.8..."
20,Mariposa,228.0,06043,Mariposa County,"POLYGON ((-120.32153 37.52440, -120.32156 37.5..."
21,Mendocino,6110.0,06045,Mendocino County,"POLYGON ((-123.83841 39.55492, -123.83965 39.5..."
22,Merced,15175.0,06047,Merced County,"POLYGON ((-120.68159 37.51863, -120.67691 37.5..."
23,Modoc,424.0,06049,Modoc County,"POLYGON ((-121.44890 41.47281, -121.44891 41.4..."
24,Mono,5770.0,06051,Mono County,"POLYGON ((-119.30890 38.00715, -119.30886 38.0..."
25,Monterey,23354.0,06053,Monterey County,"POLYGON ((-122.02681 36.54641, -122.02702 36.5..."
26,Napa,6594.0,06055,Napa County,"POLYGON ((-122.46389 38.70520, -122.46388 38.7..."
27,Nevada,10004.0,06057,Nevada County,"POLYGON ((-120.71374 39.48279, -120.71370 39.4..."
28,Orange,108576.0,06059,Orange County,"POLYGON ((-117.98910 33.58579, -117.99067 33.5..."
29,Placer,17704.0,06061,Placer County,"POLYGON ((-121.06544 39.00653, -121.06537 39.0..."
30,Plumas,774.0,06063,Plumas County,"POLYGON ((-121.36701 40.07767, -121.36688 40.0..."
31,Riverside,97699.0,06065,Riverside County,"POLYGON ((-117.67244 33.87026, -117.67257 33.8..."
32,Sacramento,77704.0,06067,Sacramento County,"POLYGON ((-121.18857 38.71431, -121.18731 38.7..."
33,San Benito,4400.0,06069,San Benito County,"POLYGON ((-121.48300 36.76505, -121.48351 36.7..."
34,San Bernardino,196184.0,06071,San Bernardino County,"POLYGON ((-117.66724 34.73433, -117.66724 34.7..."
35,San Diego,172239.0,06073,San Diego County,"POLYGON ((-117.43743 33.17953, -117.44954 33.1..."
36,San Francisco,34021.0,06075,San Francisco County,"MULTIPOLYGON (((-122.61228 37.81522, -122.5845..."
37,San Joaquin,75011.0,06077,San Joaquin County,"POLYGON ((-121.20789 38.24882, -121.20703 38.2..."
38,San Luis Obispo,7161.0,06079,San Luis Obispo County,"POLYGON ((-121.18506 35.79416, -121.18463 35.7..."
39,San Mateo,26442.0,06081,San Mateo County,"POLYGON ((-122.58711 37.58755, -122.58679 37.5..."
40,Santa Barbara,20801.0,06083,Santa Barbara County,"MULTIPOLYGON (((-120.73429 34.90069, -120.7343..."
41,Santa Clara,150978.0,06085,Santa Clara County,"POLYGON ((-122.04412 37.20049, -122.04409 37.2..."
42,Santa Cruz,19930.0,06087,Santa Cruz County,"POLYGON ((-122.21668 37.21521, -122.21651 37.2..."
43,Shasta,7932.0,06089,Shasta County,"POLYGON ((-122.61527 40.88107, -122.61473 40.8..."
44,Sierra,48.0,06091,Sierra County,"POLYGON ((-120.65559 39.69356, -120.65552 39.6..."
45,Siskiyou,1548.0,06093,Siskiyou County,"POLYGON ((-122.87087 42.00396, -122.86813 42.0..."
46,Solano,24519.0,06095,Solano County,"POLYGON ((-122.06478 38.31591, -122.06508 38.3..."
47,Sonoma,31115.0,06097,Sonoma County,"POLYGON ((-122.93506 38.31395, -122.93509 38.3..."
48,Stanislaus,47784.0,06099,Stanislaus County,"POLYGON ((-120.92225 37.73747, -120.92159 37.7..."
49,Sutter,8853.0,06101,Sutter County,"POLYGON ((-121.92833 39.19873, -121.92872 39.1..."
50,Tehama,2324.0,06103,Tehama County,"POLYGON ((-122.37148 40.37261, -122.37046 40.3..."
51,Trinity,691.0,06105,Trinity County,"POLYGON ((-123.54396 40.73294, -123.54386 40.7..."
52,Tulare,27995.0,06107,Tulare County,"POLYGON ((-118.80373 35.79035, -118.80496 35.7..."
53,Tuolumne,1595.0,06109,Tuolumne County,"POLYGON ((-120.50016 38.00412, -120.50025 38.0..."
54,Ventura,42100.0,06111,Ventura County,"MULTIPOLYGON (((-119.32922 34.22784, -119.3292..."
55,Yolo,7937.0,06113,Yolo County,"POLYGON ((-122.16494 38.64246, -122.16398 38.6..."
56,Yuba,5260.0,06115,Yuba County,"POLYGON ((-121.59768 39.12779, -121.59781 39.1..."

In [44]:
school_dropout.to_parquet('school_dropout.parquet')

/opt/tljh/user/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: this is an initial implementation of Parquet/Feather file support and associated metadata.  This is tracking version 0.1.0 of the metadata specification at https://github.com/geopandas/geo-arrow-spec

This metadata specification does not yet make stability promises.  We do not yet recommend using this in a production setting unless you are able to rewrite your Parquet/Feather files.

To further ignore this warning, you can do:
import warnings; warnings.filterwarnings('ignore', message='.*initial implementation of Parquet.*')
  """Entry point for launching an IPython kernel.

In [18]:
demographics = gpd.read_parquet('../demographics_tracts.parquet')

In [19]:
demographics.head()

,GEOID1,total_mf_10_19,geometry
0,06037137504,229.0,"POLYGON ((-118.58119 34.14318, -118.58099 34.1..."
1,06037138000,404.0,"POLYGON ((-118.60573 34.14585, -118.60561 34.1..."
2,06037139200,625.0,"POLYGON ((-118.53082 34.18024, -118.52952 34.1..."
3,06067002300,259.0,"POLYGON ((-121.50218 38.55643, -121.50184 38.5..."
4,06067002400,452.0,"POLYGON ((-121.50970 38.54070, -121.50960 38.5..."

In [20]:
demographics = demographics.rename(columns={'GEOID1':'GEOID'})

In [21]:
demographics['GEOID'] = [v[:5] for v in demographics.GEOID.values]

#06037137504

In [22]:
demographics

      GEOID  total_mf_10_19                                           geometry
0     06037           229.0  POLYGON ((-118.58119 34.14318, -118.58099 34.1...
1     06037           404.0  POLYGON ((-118.60573 34.14585, -118.60561 34.1...
2     06037           625.0  POLYGON ((-118.53082 34.18024, -118.52952 34.1...
3     06067           259.0  POLYGON ((-121.50218 38.55643, -121.50184 38.5...
4     06067           452.0  POLYGON ((-121.50970 38.54070, -121.50960 38.5...
...     ...             ...                                                ...
8052  06059           784.0  POLYGON ((-117.95917 33.92458, -117.95888 33.9...
8053  06059           438.0  POLYGON ((-117.95918 33.92820, -117.95831 33.9...
8054  06059           516.0  POLYGON ((-117.95056 33.94503, -117.95055 33.9...
8055  06013           869.0  POLYGON ((-122.34551 37.96355, -122.34550 37.9...
8056  06047          1332.0  POLYGON ((-120.65838 36.96594, -120.65833 36.9...

[8057 rows x 3 columns]

In [23]:
type(demographics)

geopandas.geodataframe.GeoDataFrame

# test case

In [24]:
case = demographics[demographics['GEOID'] == '06001']

In [25]:
case

      GEOID  total_mf_10_19                                           geometry
33    06001           639.0  POLYGON ((-122.05035 37.58349, -122.05019 37.5...
34    06001           720.0  POLYGON ((-122.08961 37.56211, -122.08955 37.5...
35    06001           695.0  POLYGON ((-122.06266 37.57135, -122.06229 37.5...
36    06001           633.0  POLYGON ((-122.06428 37.58679, -122.06313 37.5...
37    06001           434.0  POLYGON ((-122.03851 37.56341, -122.03845 37.5...
...     ...             ...                                                ...
7350  06001           185.0  POLYGON ((-122.26677 37.81155, -122.26639 37.8...
7380  06001           919.0  POLYGON ((-122.22263 37.78399, -122.22234 37.7...
7852  06001           954.0  POLYGON ((-121.87883 37.70116, -121.87883 37.7...
7853  06001           617.0  POLYGON ((-122.24097 37.78656, -122.24074 37.7...
7854  06001           698.0  POLYGON ((-121.90388 37.70585, -121.90311 37.7...

[361 rows x 3 columns]

In [26]:
case.total_mf_10_19.sum()

189657.0

# end

In [27]:
demographics.groupby(by='GEOID').sum()

       total_mf_10_19
GEOID
06001        189657.0
06003           193.0
06005          3705.0
06007         27187.0
06009          4245.0
06011          3177.0
06013        149185.0
06015          3382.0
06017         23533.0
06019        150121.0
06021          4378.0
06023         15908.0
06025         28192.0
06027          1943.0
06029        138869.0
06031         21696.0
06033          7012.0
06035          2921.0
06037       1281497.0
06039         23496.0
06041         30415.0
06043          1555.0
06045          9864.0
06047         45837.0
06049           955.0
06051          1541.0
06053         62703.0
06055         18655.0
06057         10312.0
06059        415173.0
06061         48939.0
06063          1819.0
06065        355493.0
06067        196932.0
06069          9147.0
06071        320272.0
06073        407222.0
06075         60080.0
06077        112228.0
06079         36790.0
06081         84632.0
06083         64685.0
06085        238587.0
06087         38247.0
06089         21308.0
06091           294.0
06093          4768.0
06095         54570.0
06097         58866.0
06099         80887.0
06101         13614.0
06103          8335.0
06105          1275.0
06107         78064.0
06109          4861.0
06111        116814.0
06113         33441.0
06115         10770.0

In [28]:
dem_counties = counties.merge(demographics.groupby(by='GEOID').sum(), on='GEOID')

In [29]:
dem_counties

,GEOID,NAMELSAD,CountyName,geometry,total_mf_10_19
0,06091,Sierra County,Sierra,"POLYGON ((-120.65559 39.69356, -120.65552 39.6...",294.0
1,06067,Sacramento County,Sacramento,"POLYGON ((-121.18857 38.71431, -121.18731 38.7...",196932.0
2,06083,Santa Barbara County,Santa Barbara,"MULTIPOLYGON (((-120.73429 34.90069, -120.7343...",64685.0
3,06009,Calaveras County,Calaveras,"POLYGON ((-120.63093 38.34110, -120.63057 38.3...",4245.0
4,06111,Ventura County,Ventura,"MULTIPOLYGON (((-119.32922 34.22784, -119.3292...",116814.0
5,06037,Los Angeles County,Los Angeles,"MULTIPOLYGON (((-118.70339 34.16859, -118.7033...",1281497.0
6,06097,Sonoma County,Sonoma,"POLYGON ((-122.93506 38.31395, -122.93509 38.3...",58866.0
7,06031,Kings County,Kings,"POLYGON ((-119.95892 36.25547, -119.95893 36.2...",21696.0
8,06073,San Diego County,San Diego,"POLYGON ((-117.43743 33.17953, -117.44954 33.1...",407222.0
9,06061,Placer County,Placer,"POLYGON ((-121.06544 39.00653, -121.06537 39.0...",48939.0
10,06075,San Francisco County,San Francisco,"MULTIPOLYGON (((-122.61228 37.81522, -122.5845...",60080.0
11,06041,Marin County,Marin,"POLYGON ((-122.78639 37.88695, -122.78704 37.8...",30415.0
12,06043,Mariposa County,Mariposa,"POLYGON ((-120.32153 37.52440, -120.32156 37.5...",1555.0
13,06035,Lassen County,Lassen,"POLYGON ((-121.32191 40.65496, -121.32181 40.6...",2921.0
14,06055,Napa County,Napa,"POLYGON ((-122.46389 38.70520, -122.46388 38.7...",18655.0
15,06089,Shasta County,Shasta,"POLYGON ((-122.61527 40.88107, -122.61473 40.8...",21308.0
16,06053,Monterey County,Monterey,"POLYGON ((-122.02681 36.54641, -122.02702 36.5...",62703.0
17,06105,Trinity County,Trinity,"POLYGON ((-123.54396 40.73294, -123.54386 40.7...",1275.0
18,06045,Mendocino County,Mendocino,"POLYGON ((-123.83841 39.55492, -123.83965 39.5...",9864.0
19,06027,Inyo County,Inyo,"POLYGON ((-118.33758 36.65480, -118.33773 36.6...",1943.0
20,06051,Mono County,Mono,"POLYGON ((-119.30890 38.00715, -119.30886 38.0...",1541.0
21,06109,Tuolumne County,Tuolumne,"POLYGON ((-120.50016 38.00412, -120.50025 38.0...",4861.0
22,06095,Solano County,Solano,"POLYGON ((-122.06478 38.31591, -122.06508 38.3...",54570.0
23,06071,San Bernardino County,San Bernardino,"POLYGON ((-117.66724 34.73433, -117.66724 34.7...",320272.0
24,06013,Contra Costa County,Contra Costa,"POLYGON ((-122.26764 37.90425, -122.26781 37.9...",149185.0
25,06003,Alpine County,Alpine,"POLYGON ((-120.07333 38.70109, -120.07324 38.7...",193.0
26,06017,El Dorado County,El Dorado,"POLYGON ((-121.11862 38.71712, -121.11876 38.7...",23533.0
27,06113,Yolo County,Yolo,"POLYGON ((-122.16494 38.64246, -122.16398 38.6...",33441.0
28,06115,Yuba County,Yuba,"POLYGON ((-121.59768 39.12779, -121.59781 39.1...",10770.0
29,06069,San Benito County,San Benito,"POLYGON ((-121.48300 36.76505, -121.48351 36.7...",9147.0
30,06023,Humboldt County,Humboldt,"POLYGON ((-124.28140 40.79915, -124.28018 40.7...",15908.0
31,06065,Riverside County,Riverside,"POLYGON ((-117.67244 33.87026, -117.67257 33.8...",355493.0
32,06029,Kern County,Kern,"POLYGON ((-119.91366 35.43926, -119.92327 35.4...",138869.0
33,06011,Colusa County,Colusa,"POLYGON ((-122.08018 39.41420, -122.07996 39.4...",3177.0
34,06015,Del Norte County,Del Norte,"POLYGON ((-124.31611 41.72839, -124.33061 41.7...",3382.0
35,06049,Modoc County,Modoc,"POLYGON ((-121.44890 41.47281, -121.44891 41.4...",955.0
36,06019,Fresno County,Fresno,"POLYGON ((-120.42219 36.84014, -120.42172 36.8...",150121.0
37,06039,Madera County,Madera,"POLYGON ((-120.10639 37.16715, -120.10577 37.1...",23496.0
38,06085,Santa Clara County,Santa Clara,"POLYGON ((-122.04412 37.20049, -122.04409 37.2...",238587.0
39,06103,Tehama County,Tehama,"POLYGON ((-122.37148 40.37261, -122.37046 40.3...",8335.0
40,06077,San Joaquin County,San Joaquin,"POLYGON ((-121.20789 38.24882, -121.20703 38.2...",112228.0
41,06001,Alameda County,Alameda,"POLYGON ((-122.28088 37.70723, -122.28178 37.7...",189657.0
42,06057,Nevada County,Nevada,"POLYGON ((-120.71374 39.48279, -120.71370 39.4...",10312.0
43,06007,Butte County,Butte,"POLYGON ((-121.85650 39.53358, -121.85638 39.5...",27187.0
44,06047,Merced County,Merced,"POLYGON ((-120.68159 37.51863, -120.67691 37.5...",45837.0
45,06107,Tulare County,Tulare,"POLYGON ((-118.80373 35.79035, -118.80496 35.7...",78064.0
46,06099,Stanislaus County,Stanislaus,"POLYGON ((-120.92225 37.73747, -120.92159 37.7...",80887.0
47,06059,Orange County,Orange,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",415173.0
48,06025,Imperial County,Imperial,"POLYGON ((-114.72653 32.71824, -114.72662 32.7...",28192.0
49,06101,Sutter County,Sutter,"POLYGON ((-121.92833 39.19873, -121.92872 39.1...",13614.0
50,06005,Amador County,Amador,"POLYGON ((-121.02729 38.48136, -121.02729 38.4...",3705.0
51,06033,Lake County,Lake,"POLYGON ((-123.06515 39.05918, -123.06515 39.0...",7012.0
52,06063,Plumas County,Plumas,"POLYGON ((-121.36701 40.07767, -121.36688 40.0...",1819.0
53,06081,San Mateo County,San Mateo,"POLYGON ((-122.58711 37.58755, -122.58679 37.5...",84632.0
54,06093,Siskiyou County,Siskiyou,"POLYGON ((-122.87087 42.00396, -122.86813 42.0...",4768.0
55,06087,Santa Cruz County,Santa Cruz,"POLYGON ((-122.21668 37.21521, -122.21651 37.2...",38247.0
56,06021,Glenn County,Glenn,"POLYGON ((-122.89094 39.64487, -122.89134 39.6...",4378.0
57,06079,San Luis Obispo County,San Luis Obispo,"POLYGON ((-121.18506 35.79416, -121.18463 35.7...",36790.0

In [31]:
income = gpd.read_parquet('../income_counties.parquet')

In [32]:
income.head()

,GEOID,median_household_income,median_home_value,per_capita_income,geometry
3995,06073016809,93500.0,442300.0,34675.0,"POLYGON ((6356264.930 1875989.112, 6356373.941..."
3996,06073016810,86442.0,456400.0,32102.0,"POLYGON ((6356070.107 1891633.170, 6356084.247..."
3997,06073016811,71250.0,392600.0,28095.0,"POLYGON ((6359599.903 1884610.154, 6359828.308..."
3998,06073016901,90859.0,496200.0,33304.0,"POLYGON ((6332393.436 1902845.350, 6332761.116..."
3999,06073016902,93750.0,460300.0,34894.0,"POLYGON ((6352081.727 1903549.063, 6352082.072..."

In [33]:
income['GEOID'] = [v[:5] for v in income.GEOID.values]

In [34]:
income.head()

,GEOID,median_household_income,median_home_value,per_capita_income,geometry
3995,06073,93500.0,442300.0,34675.0,"POLYGON ((6356264.930 1875989.112, 6356373.941..."
3996,06073,86442.0,456400.0,32102.0,"POLYGON ((6356070.107 1891633.170, 6356084.247..."
3997,06073,71250.0,392600.0,28095.0,"POLYGON ((6359599.903 1884610.154, 6359828.308..."
3998,06073,90859.0,496200.0,33304.0,"POLYGON ((6332393.436 1902845.350, 6332761.116..."
3999,06073,93750.0,460300.0,34894.0,"POLYGON ((6352081.727 1903549.063, 6352082.072..."

In [35]:
income = income[['GEOID', 'median_household_income','geometry']]

In [36]:
income.head()

,GEOID,median_household_income,geometry
3995,06073,93500.0,"POLYGON ((6356264.930 1875989.112, 6356373.941..."
3996,06073,86442.0,"POLYGON ((6356070.107 1891633.170, 6356084.247..."
3997,06073,71250.0,"POLYGON ((6359599.903 1884610.154, 6359828.308..."
3998,06073,90859.0,"POLYGON ((6332393.436 1902845.350, 6332761.116..."
3999,06073,93750.0,"POLYGON ((6352081.727 1903549.063, 6352082.072..."

In [37]:
income.groupby(by='GEOID').sum()

       median_household_income
GEOID
06059               53051355.0
06065               29688885.0
06071               22723588.0
06073               49410600.0

In [38]:
dem_counties.merge(income.groupby(by='GEOID').sum(), on='GEOID')

,GEOID,NAMELSAD,CountyName,geometry,total_mf_10_19,median_household_income
0,06073,San Diego County,San Diego,"POLYGON ((-117.43743 33.17953, -117.44954 33.1...",407222.0,49410600.0
1,06071,San Bernardino County,San Bernardino,"POLYGON ((-117.66724 34.73433, -117.66724 34.7...",320272.0,22723588.0
2,06065,Riverside County,Riverside,"POLYGON ((-117.67244 33.87026, -117.67257 33.8...",355493.0,29688885.0
3,06059,Orange County,Orange,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",415173.0,53051355.0

In [39]:
dem_income = dem_counties.merge(income.groupby(by='GEOID').sum(), on='GEOID')

In [40]:
dem_income

,GEOID,NAMELSAD,CountyName,geometry,total_mf_10_19,median_household_income
0,06073,San Diego County,San Diego,"POLYGON ((-117.43743 33.17953, -117.44954 33.1...",407222.0,49410600.0
1,06071,San Bernardino County,San Bernardino,"POLYGON ((-117.66724 34.73433, -117.66724 34.7...",320272.0,22723588.0
2,06065,Riverside County,Riverside,"POLYGON ((-117.67244 33.87026, -117.67257 33.8...",355493.0,29688885.0
3,06059,Orange County,Orange,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",415173.0,53051355.0

In [43]:
#dem_income.to_parquet('dem_income.parquet')

/opt/tljh/user/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: this is an initial implementation of Parquet/Feather file support and associated metadata.  This is tracking version 0.1.0 of the metadata specification at https://github.com/geopandas/geo-arrow-spec

This metadata specification does not yet make stability promises.  We do not yet recommend using this in a production setting unless you are able to rewrite your Parquet/Feather files.

To further ignore this warning, you can do:
import warnings; warnings.filterwarnings('ignore', message='.*initial implementation of Parquet.*')
  """Entry point for launching an IPython kernel.