In [1]:
import pandas
import pandas as pd 
import geopandas as gpd
import matplotlib.pyplot as plt
import contextily as ctx
from geopandas_view import view
import geopandas

In [2]:
import quilt3
b = quilt3.Bucket("s3://spatial-ucr")
b.fetch("census/demographic_profile/2018/acs_2018_X02_RACE_bg.parquet", "./acs_2018_X02_RACE_bg.parquet")

100%|██████████| 9.15M/9.15M [00:03<00:00, 2.74MB/s]

In [22]:
race_tracts = pandas.read_parquet('./acs_2018_X02_RACE_bg.parquet')

In [23]:
race_tracts.head()

,B02001_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_007E,B02001_008E,B02001_009E,B02001_010E,...,C02003_010E,C02003_011E,C02003_012E,C02003_013E,C02003_014E,C02003_015E,C02003_016E,C02003_017E,C02003_018E,C02003_019E
GEOID,,,,,,,,,,,,,,,,,,,,,
15000US021980001003,506.0,170.0,4.0,247.0,4.0,29.0,0.0,52.0,0.0,52.0,...,0.0,52.0,52.0,0.0,52.0,0.0,0.0,0.0,0.0,0.0
15000US021980002001,927.0,446.0,3.0,366.0,0.0,7.0,0.0,105.0,0.0,105.0,...,0.0,105.0,97.0,0.0,91.0,0.0,0.0,6.0,8.0,0.0
15000US021980002002,1178.0,731.0,11.0,235.0,26.0,0.0,7.0,168.0,10.0,158.0,...,10.0,158.0,152.0,6.0,121.0,10.0,1.0,14.0,16.0,0.0
15000US021980002003,435.0,321.0,0.0,55.0,9.0,0.0,0.0,50.0,2.0,48.0,...,2.0,48.0,46.0,0.0,42.0,0.0,1.0,3.0,4.0,0.0
15000US021980003001,15.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
race_tracts.columns

Index(['B02001_001E', 'B02001_002E', 'B02001_003E', 'B02001_004E',
       'B02001_005E', 'B02001_006E', 'B02001_007E', 'B02001_008E',
       'B02001_009E', 'B02001_010E', 'B02008_001E', 'B02009_001E',
       'B02010_001E', 'B02011_001E', 'B02012_001E', 'B02013_001E',
       'C02003_001E', 'C02003_002E', 'C02003_003E', 'C02003_004E',
       'C02003_005E', 'C02003_006E', 'C02003_007E', 'C02003_008E',
       'C02003_009E', 'C02003_010E', 'C02003_011E', 'C02003_012E',
       'C02003_013E', 'C02003_014E', 'C02003_015E', 'C02003_016E',
       'C02003_017E', 'C02003_018E', 'C02003_019E'],
      dtype='object')

In [7]:
race_tracts.reset_index()

,GEOID,B02001_001E,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_007E,B02001_008E,B02001_009E,...,C02003_010E,C02003_011E,C02003_012E,C02003_013E,C02003_014E,C02003_015E,C02003_016E,C02003_017E,C02003_018E,C02003_019E
0,15000US021980001003,506.0,170.0,4.0,247.0,4.0,29.0,0.0,52.0,0.0,...,0.0,52.0,52.0,0.0,52.0,0.0,0.0,0.0,0.0,0.0
1,15000US021980002001,927.0,446.0,3.0,366.0,0.0,7.0,0.0,105.0,0.0,...,0.0,105.0,97.0,0.0,91.0,0.0,0.0,6.0,8.0,0.0
2,15000US021980002002,1178.0,731.0,11.0,235.0,26.0,0.0,7.0,168.0,10.0,...,10.0,158.0,152.0,6.0,121.0,10.0,1.0,14.0,16.0,0.0
3,15000US021980002003,435.0,321.0,0.0,55.0,9.0,0.0,0.0,50.0,2.0,...,2.0,48.0,46.0,0.0,42.0,0.0,1.0,3.0,4.0,0.0
4,15000US021980003001,15.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220328,15000US560419752002,1792.0,1692.0,0.0,0.0,4.0,0.0,6.0,90.0,0.0,...,0.0,90.0,90.0,0.0,90.0,0.0,0.0,0.0,0.0,0.0
220329,15000US560419752003,1229.0,1229.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
220330,15000US560419752004,2354.0,2239.0,5.0,0.0,0.0,0.0,0.0,110.0,0.0,...,0.0,110.0,110.0,14.0,96.0,0.0,0.0,0.0,0.0,0.0
220331,15000US560419753001,2088.0,1788.0,3.0,59.0,0.0,0.0,202.0,36.0,0.0,...,0.0,36.0,36.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0
220332,15000US560419753002,1368.0,1160.0,0.0,25.0,8.0,0.0,13.0,162.0,0.0,...,0.0,162.0,162.0,0.0,162.0,0.0,0.0,0.0,0.0,0.0

In [9]:
race_tracts = race_tracts[['B02001_002E','B02001_003E','B02001_004E','B02001_005E','B02001_006E','B02001_008E']]

In [10]:
race_tracts.head()

,B02001_002E,B02001_003E,B02001_004E,B02001_005E,B02001_006E,B02001_008E
GEOID,,,,,,
15000US021980001003,170.0,4.0,247.0,4.0,29.0,52.0
15000US021980002001,446.0,3.0,366.0,0.0,7.0,105.0
15000US021980002002,731.0,11.0,235.0,26.0,0.0,168.0
15000US021980002003,321.0,0.0,55.0,9.0,0.0,50.0
15000US021980003001,15.0,0.0,0.0,0.0,0.0,0.0

In [12]:
race_tracts = race_tracts.rename(columns={'B02001_002E':'white','B02001_003E':'black','B02001_004E':'amind','B02001_005E':'asian','B02001_006E':'nh_pi','B02001_008E':'two_or_more'})

In [13]:
race_tracts.head()

                     white  black  amind  asian  nh_pi  two or more
GEOID
15000US021980001003  170.0    4.0  247.0    4.0   29.0         52.0
15000US021980002001  446.0    3.0  366.0    0.0    7.0        105.0
15000US021980002002  731.0   11.0  235.0   26.0    0.0        168.0
15000US021980002003  321.0    0.0   55.0    9.0    0.0         50.0
15000US021980003001   15.0    0.0    0.0    0.0    0.0          0.0

In [15]:
race_tracts.reset_index()

                      GEOID   white  black  amind  asian  nh_pi  two or more
0       15000US021980001003   170.0    4.0  247.0    4.0   29.0         52.0
1       15000US021980002001   446.0    3.0  366.0    0.0    7.0        105.0
2       15000US021980002002   731.0   11.0  235.0   26.0    0.0        168.0
3       15000US021980002003   321.0    0.0   55.0    9.0    0.0         50.0
4       15000US021980003001    15.0    0.0    0.0    0.0    0.0          0.0
...                     ...     ...    ...    ...    ...    ...          ...
220328  15000US560419752002  1692.0    0.0    0.0    4.0    0.0         90.0
220329  15000US560419752003  1229.0    0.0    0.0    0.0    0.0          0.0
220330  15000US560419752004  2239.0    5.0    0.0    0.0    0.0        110.0
220331  15000US560419753001  1788.0    3.0   59.0    0.0    0.0         36.0
220332  15000US560419753002  1160.0    0.0   25.0    8.0    0.0        162.0

[220333 rows x 7 columns]

In [18]:
race_tracts.columns

Index(['white', 'black', 'amind', 'asian', 'nh_pi', 'two or more'], dtype='object')

In [28]:
dem_tracts = pandas.read_parquet('demographics_tracts.parquet')

FileNotFoundError: [Errno 2] No such file or directory: 'demographics_tracts.parquet'