In [1]:
import seaborn as sns
import geopandas as gpd
import matplotlib.pyplot as plt
import contextily as ctx
from geopandas_view import view
plt.rcParams['figure.figsize'] = [20,10]

In [2]:
gpd.read_parquet("schoolcounties.parquet")

,geoid,geometry,fips,name,state,CountyName,ChronicAbsenteeismCount,CumulativeEnrollment,absentrate,Unnamed: 0,...,SPED Certificate (Count),SPED Certificate (Rate),GED Completer (Count),GED Completer (Rate),Other Transfer (Count),Other Transfer (Rate),Dropout (Count),Dropout (Rate),Still Enrolled (Count),Still Enrolled (Rate)
6,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4014,...,147,0.7,4,0.0,80,0.4,824,4.2,344,1.8
14,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4015,...,263,1.3,21,0.1,155,0.8,1178,5.7,590,2.9
22,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4016,...,*,*,*,*,*,*,*,*,*,*
30,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4017,...,72,1.1,1,0.0,16,0.2,158,2.3,51,0.8
38,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4018,...,9,1.5,1,0.2,1,0.2,51,8.2,25,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130648,06073,"POLYGON ((-117.43743 33.17953, -117.44954 33.1...",06073,San Diego,CA,San Diego,579235.0,5064892.0,0.114363,207542,...,0,0.0,0,0.0,0,0.0,1,5.0,12,60.0
130649,06073,"POLYGON ((-117.43743 33.17953, -117.44954 33.1...",06073,San Diego,CA,San Diego,579235.0,5064892.0,0.114363,207543,...,0,0.0,0,0.0,0,0.0,1,5.6,9,50.0
130650,06073,"POLYGON ((-117.43743 33.17953, -117.44954 33.1...",06073,San Diego,CA,San Diego,579235.0,5064892.0,0.114363,207544,...,0,0.0,1,6.3,0,0.0,1,6.3,8,50.0
130651,06073,"POLYGON ((-117.43743 33.17953, -117.44954 33.1...",06073,San Diego,CA,San Diego,579235.0,5064892.0,0.114363,207545,...,0,0.0,4,4.8,1,1.2,5,6.0,29,34.9
130652,06073,"POLYGON ((-117.43743 33.17953, -117.44954 33.1...",06073,San Diego,CA,San Diego,579235.0,5064892.0,0.114363,207546,...,0,0.0,4,4.3,1,1.1,6,6.5,32,34.4

In [3]:
schoolcounties = gpd.read_parquet("schoolcounties.parquet")

In [5]:
schoolcounties.head()

,geoid,geometry,fips,name,state,CountyName,ChronicAbsenteeismCount,CumulativeEnrollment,absentrate,Unnamed: 0,...,SPED Certificate (Count),SPED Certificate (Rate),GED Completer (Count),GED Completer (Rate),Other Transfer (Count),Other Transfer (Rate),Dropout (Count),Dropout (Rate),Still Enrolled (Count),Still Enrolled (Rate)
6,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4014,...,147,0.7,4,0.0,80,0.4,824,4.2,344,1.8
14,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4015,...,263,1.3,21,0.1,155,0.8,1178,5.7,590,2.9
22,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4016,...,*,*,*,*,*,*,*,*,*,*
30,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4017,...,72,1.1,1,0.0,16,0.2,158,2.3,51,0.8
38,06059,"POLYGON ((-117.98910 33.58579, -117.99067 33.5...",06059,Orange,CA,Orange,470658.0,5351478.0,0.087949,4018,...,9,1.5,1,0.2,1,0.2,51,8.2,25,4.0